version: '3'
services:
  web:
    build: .
    volumes:
      - .:/webapp
    ports:
      - 3000:3000
    command: sh /webapp/scripts/startup.sh
    links:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=webapp